eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8762
spring:
    application:
        name: config-client
    cloud:
        config:
            lable: master
            profile: dev
            #uri: http://localhost:8888/
            #通过euraka自动发现
            discovery:
              enabled: true
              serviceId: config-server

management:
  security:
    enabled: false  #忽略权限拦截